### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback4-extension-grpc#3]
We should configure Travis CI and AppVeyor to run tests for all new pull requests. Let's use loopback-next's config as a template:

 - https://github.com/strongloop/loopback-next/blob/master/.travis.yml
 - https://github.com/strongloop/loopback-next/blob/master/appveyor.yml

**Comment by bajtos** [comment]
FWIW, I have enabled Travis CI for this repo - see https://travis-ci.org/strongloop/loopback4-extension-grpc

**Comment by jonathan-casarrubias** [comment]
Awesome!

**Comment by bajtos** [comment]
We will need to setup AppVeyor, probably after #8 is landed.
